version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zero-shot-classification-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19hyippceypaw"
s3_prefix = "zero-shot-classification-2"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["pytorchEndpoint=067996507694.dkr.ecr.eu-central-1.amazonaws.com/zero-shot-classification-2"]
